# Generated by Django 3.1.4 on 2021-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalfacilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldiary',
            name='image',
            field=models.ImageField(blank=True, upload_to='DigitalFacilities/DigitalDiary'),
        ),
        migrations.AlterField(
            model_name='digitalvisitingcard',
            name='image',
            field=models.ImageField(blank=True, upload_to='DigitalFacilities/DigitalVisitingCard'),
        ),
    ]
