# Generated by Django 3.1.4 on 2021-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(blank=True, null=True, upload_to='Ecommerce/Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='Ecommerce/Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='Ecommerce/Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(blank=True, null=True, upload_to='Ecommerce/Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image5',
            field=models.ImageField(blank=True, null=True, upload_to='Ecommerce/Products'),
        ),
    ]
