# Generated by Django 3.1.4 on 2021-04-05 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='DigitalProfile/Company/')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('other_link', models.URLField(blank=True, null=True)),
                ('digital_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='digitalprofile.digitalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('service_image1', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Services/')),
                ('service_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('service_image2', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Services/')),
                ('service_name3', models.CharField(blank=True, max_length=50, null=True)),
                ('service_image3', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Services/')),
                ('digital_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='digitalprofile.digitalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('designation', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('whatsapp', models.CharField(max_length=12, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=40, null=True)),
                ('about_us', models.TextField(max_length=250, null=True)),
                ('digital_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='digitalprofile.digitalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytm_number', models.CharField(blank=True, max_length=12, null=True)),
                ('paytm_qr_code', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/PaymentDetail/')),
                ('google_pay_number', models.CharField(blank=True, max_length=12, null=True)),
                ('google_pay_qr_code', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/PaymentDetail/')),
                ('phonepe_number', models.CharField(blank=True, max_length=12, null=True)),
                ('phonepe_qr_code', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/PaymentDetail/')),
                ('account_number', models.CharField(max_length=40, null=True)),
                ('account_holder_name', models.CharField(max_length=50, null=True)),
                ('re_account_number', models.CharField(max_length=40, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('branch_name', models.CharField(max_length=60, null=True)),
                ('gst_number', models.CharField(max_length=60, null=True)),
                ('digital_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='digitalprofile.digitalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Gallery/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Gallery')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Gallery')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Gallery')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Gallery')),
                ('digital_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='digitalprofile.digitalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Ecommerce/')),
                ('product_name', models.CharField(blank=True, max_length=80, null=True)),
                ('product_mrp', models.CharField(blank=True, max_length=100, null=True)),
                ('selling_price', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('digital_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='digitalprofile.digitalprofile')),
            ],
        ),
    ]
