# Generated by Django 3.1.4 on 2021-04-07 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerce',
            name='digital_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='digital_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='digital_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='digital_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='services',
            name='digital_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='digital_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
    ]
