# Generated by Django 3.1.4 on 2021-04-07 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitalprofile', '0002_auto_20210407_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalprofile',
            name='company_logo',
            field=models.ImageField(upload_to='DigitalProfile/Company/'),
        ),
        migrations.AlterField(
            model_name='digitalprofile',
            name='company_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='digitalprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.user'),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='digital_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/Ecommerce/'),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='product_mrp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='product_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='selling_price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='digital_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image1',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/Gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/Gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image3',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/Gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image4',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/Gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image5',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/Gallery'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='account_holder_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='account_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='branch_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='digital_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='google_pay_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='google_pay_qr_code',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/PaymentDetail/'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='gst_number',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='ifsc_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='paytm_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='paytm_qr_code',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/PaymentDetail/'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='phonepe_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='phonepe_qr_code',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/PaymentDetail/'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='re_account_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='about_us',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='designation',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='digital_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='location',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='whatsapp',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='services',
            name='digital_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image1',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/Services/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image2',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/Services/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image3',
            field=models.ImageField(blank=True, upload_to='DigitalProfile/Services/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='digital_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalprofile.digitalprofile'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='other_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
