# Generated by Django 3.1.4 on 2021-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalprofile', '0005_auto_20210408_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerce',
            name='product_mrp',
            field=models.IntegerField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='selling_price',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
