# Generated by Django 3.1.4 on 2021-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalprofile', '0006_auto_20210408_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='DigitalProfile/Company/'),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='product_mrp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='selling_price',
            field=models.IntegerField(blank=True),
        ),
    ]
